os:
  - linux
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install .
  - pip install coverage
  - pip install codecov
script:
  - coverage run -m unittest discover
# Push the results back to codecov
after_success:
  - codecov
